spring:
  datasource:
    username: kmatheis
    password: root
    url: jdbc:mysql://localhost:3306/vet_api_demo?serverTimezone=America/New_York


logging:
    level:
        root: warn
        '[com.kmatheis.vet]': debug